export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST'
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS'
export const USER_LOGIN_FAIL = 'USER_LOGIN_FAIL'
export const USER_LOGOUT = 'USER_LOGOUT'

export const USER_REGISTER_REQUEST = 'USER_REGISTER_REQUEST'
export const USER_REGISTER_SUCCESS = 'USER_REGISTER_SUCCESS'
export const USER_REGISTER_FAIL = 'USER_REGISTER_FAIL'

export const CREATE_LIST_REQUEST = 'CREATE_LIST_REQUEST'
export const CREATE_LIST_SUCCESS = 'CREATE_LIST_SUCCESS'
export const CREATE_LIST_FAIL = 'CREATE_LIST_FAIL'
export const CREATE_LIST_RESET = 'CREATE_LIST_RESET'

export const CREATE_TASK_REQUEST = 'CREATE_TASK_REQUEST'
export const CREATE_TASK_SUCCESS = 'CREATE_TASK_SUCCESS'
export const CREATE_TASK_FAIL = 'CREATE_TASK_FAIL'
export const CREATE_TASK_RESET = 'CREATE_TASK_RESET'

export const UPDATE_LIST_REQUEST = 'UPDATE_LIST_REQUEST'
export const UPDATE_LIST_SUCCESS = 'UPDATE_LIST_SUCCESS'
export const UPDATE_LIST_FAIL = 'UPDATE_LIST_FAIL'
export const UPDATE_LIST_RESET = 'UPDATE_LIST_RESET'

export const UPDATE_TASK_REQUEST = 'UPDATE_TASK_REQUEST'
export const UPDATE_TASK_SUCCESS = 'UPDATE_TASK_SUCCESS'
export const UPDATE_TASK_FAIL = 'UPDATE_TASK_FAIL'
export const UPDATE_TASK_RESET = 'UPDATE_TASK_RESET'

export const DELETE_LIST_REQUEST = 'DELETE_LIST_REQUEST'
export const DELETE_LIST_SUCCESS = 'DELETE_LIST_SUCCESS'
export const DELETE_LIST_FAIL = 'DELETE_LIST_FAIL'
export const DELETE_LIST_RESET = 'DELETE_LIST_RESET'

export const DELETE_TASK_REQUEST = 'DELETE_TASK_REQUEST'
export const DELETE_TASK_SUCCESS = 'DELETE_TASK_SUCCESS'
export const DELETE_TASK_FAIL = 'DELETE_TASK_FAIL'
export const DELETE_TASK_RESET = 'DELETE_TASK_RESET'
